name:                yat
version:             0.0.0
github:              "zewalldev/yat"
license:             MIT
author:              "Denis Shirokov"
maintainer:          "zewalldev@yandex.ru"
copyright:           "2024 Denis Shirokov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zewalldev/yat#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- directory
- filepath
- process
- temporary
- transformers
- rainbow
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:
    - src
    - src/opts

executables:
  yat:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yat
